temphumi/config/routes.rb
Rails.application.routes.draw do
  get 'gettemphumi/getdata'

  get 'gettemphumi/index'

  get 'gettemphumi/getdaydata'

  get 'gettemphumi/getmonthdata'

   root 'gettemphumi#index'

end

temphumi/app/models/curth.rb
class Curth < ActiveRecord::Base
end

temphumi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

temphumi/app/controllers/gettemphumi_controller.rb
class GettemphumiController < ApplicationController
  
  def index
    t=Time.now
    date_str = t.strftime("%Y-%m-%d")
    @date=date_str
  end


  def getdata#Ajax刷新的
  	t=Time.current
  	date_str = t.strftime("%Y-%m-%d")
  	th= Curth.where("date= ?",date_str).last
  	@temp=th.temp
  	@humi=th.humi
    @location=th.location
  end

  def getdaydata
      @maxtemp=[] 
      @mintemp =[]
      @maxhumi =[]
      @minhumi=[]
    t=Time.now
    date_str = t.strftime("%Y-%m-%d")
    @date=date_str
    for i in 0..t.hour
      #第i小时的temp以升序排列
      i_T_record = Curth.where("date= ? and hour= ?",date_str,i).order("temp")#.last
      #第i小时的humi以升序排列
      i_H_record = Curth.where("date= ? and hour= ?",date_str,i).order("humi")
      if i_T_record.last
        @maxtemp[i] = i_T_record.last.temp.to_f
        @mintemp[i] = i_T_record.first.temp.to_f
        @maxhumi[i] = i_H_record.last.humi.to_f
        @minhumi[i] = i_H_record.first.humi.to_f
      else
        @maxtemp[i] = nil
        @mintemp[i] = nil
        @maxhumi[i] = nil
        @minhumi[i] = nil
      end
    end
  end

  def getmonthdata
      @maxtemp=[] 
      @mintemp =[]
      @maxhumi =[]
      @minhumi=[]
      @date = []
      t=Time.now
      
    for i in (-29)..0
       j = 30 + i
      date_str=(t+i*60*60*24).strftime("%Y-%m-%d")
      #date_str1=(t+i*60*60*24).strftime("%Y-%m-%d")
      @date[j] = date_str

      i_T_record = Curth.where("date= ? ",date_str).order("temp")
      i_H_record = Curth.where("date= ? ",date_str).order("humi")

     
      if i_T_record.last
        @maxtemp[j] = i_T_record.last.temp.to_f
        @mintemp[j] = i_T_record.first.temp.to_f
        @maxhumi[j] = i_H_record.last.humi.to_f
        @minhumi[j] = i_H_record.first.humi.to_f
      else
        @maxtemp[j] = nil
        @mintemp[j] = nil
        @maxhumi[j] = nil
        @minhumi[j] = nil
      end
      #@date = JSON.parse(date)
    end
   
  end

end

temphumi/app/helpers/application_helper.rb
module ApplicationHelper
end

temphumi/app/helpers/gettemphumi_helper.rb
module GettemphumiHelper
end

temphumi/app/helpers/home_helper.rb
module HomeHelper
end

temphumi/app/views/gettemphumi/getdata.html.erb
<%=@temp%> <%=@humi%> <%=@location%>

temphumi/app/views/gettemphumi/getdaydata.html.erb
<!doctype html>
<html lang="en">
<head>
   <!--<script type="text/javascript" src="http://cdn.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
   <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
   <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/exporting.js"></script> -->
   <title>Today's Temperature and Humidity data</title>
   <!-- // <script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script> -->
   <!-- // <script src="http://code.highcharts.com/highcharts.js"></script> -->
   <script src="/jquery-2.1.4.min.js"></script>
   <script src="/Highcharts-4.2.1/js/highcharts.js"></script>
  
</head>
<body>
    <%#=@record.to_json%>
  <div id="container" style="min-width:350px;height:280px"></div>
  <div align="center">
    <%#=link_to "30 days' graph", gettemphumi_getmonthdata_path %>
    <%=link_to "Back", gettemphumi_index_path %>
  </div>
<script>
    $(function () {
    $('#container').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: "<%=@date%>" +':A Day T&H of graph'
        },
        // subtitle: {
        //     text: 'Source: WorldClimate.com'
        // },
        xAxis: [{
            categories: ['0','1', '2', '3', '4', '5', '6','7', '8', '9', '10', '11', '12', '13', '14', '15', '16','17', '18', '19', '20', '21', '22','23']
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}°C',
                style: {
                    color: '#89A54E'
                }
            },
            title: {
                text: 'Temperature',
                style: {
                    color: '#89A54E'
                }
            },
            //min:-10,
            minRange: 0.2
        }, { // Secondary yAxis
            title: {
                text: 'Humidity',
                style: {
                    color: '#4572A7'
                }
            },
            labels: {
                format: '{value} %',
                style: {
                    color: '#4572A7'
                }
            },
           // min:0,
           minRange: 5,
             opposite: true
        }],
        tooltip: {
            shared: true
        },
        legend: {
            layout: 'horizontal',
            align: 'center',
            x: 0,
            verticalAlign: 'top',
            y: 20,
            floating: false,
            backgroundColor: '#FFFFFF'
        },
        series: [{
            name: 'MaxT',
            //color: '#4572A7',
            color: '#89A54E',
            type: 'spline',
            //yAxis: 1,
            data: <%=@maxtemp.to_json%>,//[49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
            tooltip: {
                valueSuffix: '°C'
            }

        }, {
            name: 'MinT',
            //color: '#4572A7',
            color: '#89A54E',
            type: 'spline',
            //yAxis: 1,
            data: <%=@mintemp.to_json%>,//[49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
            tooltip: {
                valueSuffix: '°C'
            }

        },{
            name: 'MaxH',
            //color: '#89A54E',
            color: '#4572A7',
            type: 'spline',
            yAxis: 1,
            data: <%=@maxhumi.to_json%>,//[7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6],
            tooltip: {
                valueSuffix: '%'
            }
        },{
            name: 'MinH',
            //color: '#89A54E',
            color: '#4572A7',
            type: 'spline',
            yAxis: 1,
            data: <%=@minhumi.to_json%>,//[7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6],
            tooltip: {
                valueSuffix: '%'
            }
        }]
    });
});

Highcharts.theme = { 
   colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
    chart: { 
      backgroundColor: { 
                           linearGradient: { x1: 0, y1: 0, x2: 1, y2: 1 }, 
                                    stops: [ [0, 'rgb(255, 255, 255)'], [1, 'rgb(240, 240, 255)'] ] 
                        },
                           borderWidth: 2, 
                           plotBackgroundColor: 'rgba(255, 255, 255, .9)', 
                           plotShadow: true, plotBorderWidth: 1 
                     }, 
       title: { 
                  style: { color: '#000', font: 'bold 16px "Trebuchet MS", Verdana, sans-serif' } 
               }, 

       subtitle: { 
                  style: { color: '#666666', font: 'bold 12px "Trebuchet MS", Verdana, sans-serif' } 
               },

       legend: { 
                  itemStyle: { font: '9pt Trebuchet MS, Verdana, sans-serif', color: 'black' }, 
               itemHoverStyle: { color: '#039' }, itemHiddenStyle: { color: 'gray' } 
               },

       labels: { 
                  style: { color: '#99b' } 
               },

       navigation: { buttonOptions: { theme: { stroke: '#CCCCCC' } } } 
    }; 
// Apply the theme 
var highchartsOptions = Highcharts.setOptions(Highcharts.theme);
  </script>
</body>
</html>

temphumi/app/views/gettemphumi/getmonthdata.html.erb
<!doctype html>
<html lang="en">
<head>
   <!--<script type="text/javascript" src="http://cdn.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
   <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
   <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/exporting.js"></script> -->
   <title>30 days Temperature and Humidity data</title>
   <!-- // <script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script> -->
   <!-- // <script src="http://code.highcharts.com/highcharts.js"></script> -->
   <script src="/jquery-2.1.4.min.js"></script>
   <script src="/Highcharts-4.2.1/js/highcharts.js"></script>
  
</head>
<body>
    <%#=@date%>
  <div id="container" style="min-width:350px;height:280px"></div>
  <div align="center">
    <%#=link_to "Today T&H graph", gettemphumi_getdaydata_path %>&nbsp&nbsp|&nbsp&nbsp
    <%=link_to "Back", gettemphumi_index_path %>
  </div>
<script>
    $(function () {
    $('#container').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: '30 Days T&H of graph'
        },
        // subtitle: {
        //     text: 'Source: WorldClimate.com'
        // },
        xAxis: {
                   //type:'category',  
                   //categories:<%=@date%>
                   type: 'datetime',
            dateTimeLabelFormats: {
                day: '%e. %b'
            }
        },
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}°C',
                style: {
                    color: '#89A54E'
                }
            },
            title: {
                text: 'Temperature',
                style: {
                    color: '#89A54E'
                }
            },
            min:-10,
            minRange: 2,
        }, { // Secondary yAxis
            title: {
                text: 'Humidity',
                style: {
                    color: '#4572A7'
                }
            },
            labels: {
                format: '{value} %',
                style: {
                    color: '#4572A7'
                }
            },
            min:0,
            minRange: 10,
             opposite: true
        }],
        tooltip: {
            shared: true
        },
        legend: {
            layout: 'horizontal',
            align: 'center',
            x: 0,
            verticalAlign: 'top',
            y: 20,
            floating: false,
            backgroundColor: '#FFFFFF'
        },
        series: [{
            name: 'MaxT',
            //color: '#4572A7',
            color: '#89A54E',
            type: 'spline',
            //yAxis: 1,
            data: <%=@maxtemp.to_json%>,//[49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
            tooltip: {
                valueSuffix: '°C'
            }

        }, {
            name: 'MinT',
            //color: '#4572A7',
            color: '#89A54E',
            type: 'spline',
            //yAxis: 1,
            data: <%=@mintemp.to_json%>,//[49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
            tooltip: {
                valueSuffix: '°C'
            }

        },{
            name: 'MaxH',
            //color: '#89A54E',
            color: '#4572A7',
            type: 'spline',
            yAxis: 1,
            data: <%=@maxhumi.to_json%>,//[7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6],
            tooltip: {
                valueSuffix: '%'
            }
        },{
            name: 'MinH',
            //color: '#89A54E',
            color: '#4572A7',
            type: 'spline',
            yAxis: 1,
            data: <%=@minhumi.to_json%>,//[7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6],
            tooltip: {
                valueSuffix: '%'
            }
        }],
         pointStart: Date.UTC(2016, 0, 1),
         pointInterval: 24 * 3600 * 1000 // one day
    });
});

Highcharts.theme = { 
   colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
    chart: { 
      backgroundColor: { 
                           linearGradient: { x1: 0, y1: 0, x2: 1, y2: 1 }, 
                                    stops: [ [0, 'rgb(255, 255, 255)'], [1, 'rgb(240, 240, 255)'] ] 
                        },
                           borderWidth: 2, 
                           plotBackgroundColor: 'rgba(255, 255, 255, .9)', 
                           plotShadow: true, plotBorderWidth: 1 
                     }, 
       title: { 
                  style: { color: '#000', font: 'bold 16px "Trebuchet MS", Verdana, sans-serif' } 
               }, 

       subtitle: { 
                  style: { color: '#666666', font: 'bold 12px "Trebuchet MS", Verdana, sans-serif' } 
               },

       legend: { 
                  itemStyle: { font: '9pt Trebuchet MS, Verdana, sans-serif', color: 'black' }, 
               itemHoverStyle: { color: '#039' }, itemHiddenStyle: { color: 'gray' } 
               },

       labels: { 
                  style: { color: '#99b' } 
               },

       navigation: { buttonOptions: { theme: { stroke: '#CCCCCC' } } } 
    }; 
// Apply the theme 
var highchartsOptions = Highcharts.setOptions(Highcharts.theme);
  </script>
</body>
</html>

temphumi/app/views/gettemphumi/index.html.erb
<!doctype html>
<html lang="en">
<head>
   <!--<script type="text/javascript" src="http://cdn.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
   <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
   <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/exporting.js"></script> -->
   <title>Today's Temperature and Humidity data</title>
   <!-- // <script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script> -->
   <!-- // <script src="http://code.highcharts.com/highcharts.js"></script> -->
   <script src="/jquery-2.1.4.min.js"></script>
   <script src="/Highcharts-4.2.1/js/highcharts.js"></script>
  
</head>
<body>
  <div id="container" style="min-width:350px;height:290px"></div>
  <div align="center">
    <%=link_to "Today's graph", gettemphumi_getdaydata_path %>
    <%#=link_to "30 days' graph", gettemphumi_getmonthdata_path %>
    <%#=link_to "Back", gettemphumi_index_path %>
</div>
<script>
  var temp,humi,place;
   function getdata(){
         $.ajax({
                    type: "GET",
                    url: "./getdata",//"http://192.168.192.169:3000/gettemphumi/getdata",
                    dataType:"html",
                    async: false, //表示同步，如果要得到ajax处理完后台数据后的返回值，最好这样设置
                    success: function(data){
                              var arr=data.split(" ");
                              temp = parseInt(arr[0]);
                              humi = parseInt(arr[1]);
                              place = arr[2];
                              //alert(place) ;
                              }
                      }); 
          
   }

    $(function () {
    $('#container').highcharts({
        chart: {
            type: 'line',
            animation: Highcharts.svg, // don't animate in IE < IE 10.
            marginRight: 80,
            zoomType: 'y',
             events: {
                 load: function () {
                    // set up the updating of the chart each second
                    var series1 = this.series[0];
                    var series2 = this.series[1];
                    setInterval(function () {
                       getdata();
                       var cur_time = ((new Date()).getTime()+3600*1000*8); // current time
                       series1.addPoint([cur_time, temp], true, true);
                       series2.addPoint([cur_time, humi], true, true);
                    }, 1000*10);
                 }
              }
        },
        title: {
            text: "<%=@date%>" +':ENG-OFFICE T&H Live data'
        },
        // subtitle: {
        //     text: 'Source: WorldClimate.com'
        // },
        // plotOptions:{
        //       line: {
        //                series :{
        //                   dataLabels: {
        //                      enabled: true
        //                      }
        //                }
        //             }
        //    },

        xAxis: [{
                  type: 'datetime',
                  tickPixelInterval: 80
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}°C',
                style: {
                    color: '#89A54E'
                }
            },
            title: {
                text: 'Temperature',
                style: {
                    color: '#89A54E'
                }
            },
            //min:-10,
            minRange: 1
        }, { // Secondary yAxis
            title: {
                text: 'Humidity',
                style: {
                    color: '#4572A7'
                }
            },
            labels: {
                format: '{value} %',
                style: {
                    color: '#4572A7'
                }
            },
             //min:0,
          minRange: 10,
          
            opposite: true
        }],
        tooltip: {
            shared: true
        },
        // legend: {
        //     layout: 'horizontal',
        //     align: 'center',
        //     x: 10,
        //     verticalAlign: 'top',
        //     y: 15,
        //     floating: true,
        //     backgroundColor: '#FFFFFF'
        // },
        legend: {
            layout: 'horizontal',
            align: 'center',
            x: 0,
            verticalAlign: 'top',
            y: 15,
            floating: true,
            backgroundColor: '#FFFFFF'
        },
        series: [{
            name: 'Temperature',
            //color: '#4572A7',
            color: '#89A54E',
            type: 'spline',
            //yAxis: 1,
            data: (function () {
         // generate an array of random data
                                 var data = [],time = ((new Date()).getTime()+3600*1000*8),i;
                                 for (i = -9; i <= 0; i += 1) {
                                    data.push({
                                       x: time + i * 10000,
                                       y: temp//Math.random()
                                    });
                                 }
                                 return data;
                              }()) ,
            tooltip: {
                valueSuffix: '°C'
            }

        }, {
            name: 'Humidity',
            //color: '#89A54E',
            color: '#4572A7',
            type: 'spline',
            yAxis: 1,
            data: (function () {
         // generate an array of random data
                                 var data = [],time = ((new Date()).getTime()+3600*8*1000),i;
                                 for (i = -9; i <= 0; i += 1) {
                                    data.push({
                                       x: time + i * 10000,
                                       y: humi//Math.random()
                                    });
                                 }
                                 return data;
                              }()),
            tooltip: {
                valueSuffix: '%'
            }
        }]
    });
});

Highcharts.theme = { 
   colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
    chart: { 
      backgroundColor: { 
                           linearGradient: { x1: 0, y1: 0, x2: 1, y2: 1 }, 
                                    stops: [ [0, 'rgb(255, 255, 255)'], [1, 'rgb(240, 240, 255)'] ] 
                        },
                           borderWidth: 2, 
                           plotBackgroundColor: 'rgba(255, 255, 255, .9)', 
                           plotShadow: true, plotBorderWidth: 1 
                     }, 
       title: { 
                  style: { color: '#000', font: 'bold 16px "Trebuchet MS", Verdana, sans-serif' } 
               }, 

       subtitle: { 
                  style: { color: '#666666', font: 'bold 12px "Trebuchet MS", Verdana, sans-serif' } 
               },

       legend: { 
                  itemStyle: { font: '9pt Trebuchet MS, Verdana, sans-serif', color: 'black' }, 
               itemHoverStyle: { color: '#039' }, itemHiddenStyle: { color: 'gray' } 
               },

       labels: { 
                  style: { color: '#99b' } 
               },

       navigation: { buttonOptions: { theme: { stroke: '#CCCCCC' } } } 
    }; 
// Apply the theme 
var highchartsOptions = Highcharts.setOptions(Highcharts.theme);
  </script>
</body>
</html>

temphumi/app/views/layouts/application.html.erb
<%=yield %>

temphumi/app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Temphumi</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
 <body>

<%=yield %>

</body>
</html>